#!/bin/bash
#LLAMA SERVER Script
#suppose model is at /workspace/llamacpp/models

docker run --rm -it --no-healthcheck --name llamacpp --hostname llamacpp --gpus all -v /workspace/llamacpp/models:/models ghcr.io/ggml-org/llama.cpp:server-cuda-b6097 -m /models/gpt-oss-20b-mxfp4.gguf --port 31415 --host 172.17.0.2 --api-key "OPEN_API_KEY" -ngl 8
